# Playground for Association Rule Learning slides

- Sourabh
- MMA 869

In [1]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Example of converting lists into a dataframe

In [2]:
#dataset = pd.read_csv("AR categories.csv")

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder #need to install mlxtend

#te = TransactionEncoder()
#te_ary = te.fit(dataset).transform(dataset)
#df1 = pd.DataFrame(te_ary, columns=te.columns_)
#df1pip

# Read in Data

In [10]:
#df = pd.read_csv("AR categories.csv")

df = pd.read_csv("AR Visits by Visit ID - luxury.csv")

X = df.copy()
X = X.drop(['Unnamed: 0', 'Visit_ID', 'Visit_ID_AR', 'Dine.on.3', 'Customer_ID', 'Hudson.s.Bay.Corridor'], axis=1) #axis 0 to drop rows


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139302 entries, 0 to 139301
Columns: 244 entries, Unnamed: 0 to Customer_ID
dtypes: bool(241), float64(1), int64(2)
memory usage: 35.2 MB

In [9]:
X.head()
X.shape

,Aldo,Aldo.Accessories,Alex.and.Ani,AllSaints,American.Eagle.Outfitters,Ann.Taylor,Anthropologie,Apple,Arc.teryx,Aritzia,...,West.Expansion.West.Entrance,White.House.Black.Market,Wilfred,Williams.Sonoma,WirelessWave,Wolford,Xpress,Zara,Zara.Home,Customer_ID
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,7121
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,3219
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,5296
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,1913
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,396

(139302, 240)

In [11]:
from mlxtend.frequent_patterns import apriori

%time frequent_itemsets = apriori(X, min_support=0.01, use_colnames=True)

Wall time: 8.55 s

In [ ]:
frequent_itemsets.head(10)

In [ ]:
frequent_itemsets.tail(10)

In [12]:
frequent_itemsets.sort_values(by=['support'], ascending=False).head()

      support                    itemsets
59   0.269056              (Hudson.s.Bay)
137  0.178196       (Sport.Chek.Entrance)
60   0.155547     (Hudson.s.Bay.Corridor)
64   0.092375           (Indigo.Entrance)
13   0.086890  (Banana.Republic.Entrance)

In [13]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

In [ ]:
frequent_itemsets.head()

In [14]:
frequent_itemsets[ (frequent_itemsets['length'] >= 2)  ]

      support                                           itemsets  length
171  0.017322          (Hudson.s.Bay, American.Eagle.Outfitters)       2
172  0.011780  (American.Eagle.Outfitters, Hudson.s.Bay.Corri...       2
173  0.020186                              (Hudson.s.Bay, Apple)       2
174  0.012670                     (Apple, Hudson.s.Bay.Corridor)       2
175  0.012713                       (Sport.Chek.Entrance, Apple)       2
..        ...                                                ...     ...
271  0.013711  (Hudson.s.Bay, Victorias.Secret, Hudson.s.Bay....       3
272  0.018169  (Indigo.Entrance, Hudson.s.Bay, Sport.Chek.Ent...       3
273  0.014056  (Hudson.s.Bay, The.Cheesecake.Factory, Victori...       3
274  0.011895  (Indigo.Entrance, Sport.Chek.Entrance, Hudson....       3
275  0.010208     (Indigo.Entrance, Indigo, Sport.Chek.Entrance)       3

[105 rows x 3 columns]

In [15]:
from mlxtend.frequent_patterns import association_rules
%time rules = association_rules(frequent_itemsets, min_threshold=0.1)

Wall time: 6.82 ms

In [16]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(American.Eagle.Outfitters),(Hudson.s.Bay),0.035190,0.269056,0.017322,0.492248,1.829539,0.007854,1.439570,1
1,(American.Eagle.Outfitters),(Hudson.s.Bay.Corridor),0.035190,0.155547,0.011780,0.334761,2.152156,0.006307,1.269399,1
2,(Apple),(Hudson.s.Bay),0.060315,0.269056,0.020186,0.334682,1.243914,0.003958,1.098639,1
3,(Apple),(Hudson.s.Bay.Corridor),0.060315,0.155547,0.012670,0.210069,1.350519,0.003288,1.069021,1
4,(Apple),(Sport.Chek.Entrance),0.060315,0.178196,0.012713,0.210783,1.182875,0.001966,1.041291,1
...,...,...,...,...,...,...,...,...,...,...
177,"(Indigo.Entrance, Indigo)",(Sport.Chek.Entrance),0.013417,0.178196,0.010208,0.760835,4.269661,0.007817,3.436135,2
178,"(Indigo.Entrance, Sport.Chek.Entrance)",(Indigo),0.058908,0.025685,0.010208,0.173288,6.746602,0.008695,1.178542,2
179,"(Indigo, Sport.Chek.Entrance)",(Indigo.Entrance),0.015965,0.092375,0.010208,0.639388,6.921674,0.008733,2.516906,2
180,(Indigo.Entrance),"(Indigo, Sport.Chek.Entrance)",0.092375,0.015965,0.010208,0.110507,6.921674,0.008733,1.106287,1
181,(Indigo),"(Indigo.Entrance, Sport.Chek.Entrance)",0.025685,0.058908,0.010208,0.397429,6.746602,0.008695,1.561794,1

In [17]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.5) &
       (rules['lift'] > 1.2) ].sort_values(by="support", ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
147,"(Sport.Chek.Entrance, Hudson.s.Bay.Corridor)",(Hudson.s.Bay),0.034472,0.269056,0.018306,0.531029,1.973676,0.009031,1.558612,2
163,"(Indigo.Entrance, Hudson.s.Bay)",(Sport.Chek.Entrance),0.028449,0.178196,0.018169,0.638658,3.584026,0.013100,2.274309,2
152,"(The.Cheesecake.Factory, Hudson.s.Bay.Corridor)",(Hudson.s.Bay),0.023733,0.269056,0.016374,0.689958,2.564367,0.009989,2.357563,2
140,"(Hudson.s.Bay.Corridor.Entrance, Hudson.s.Bay)",(Hudson.s.Bay.Corridor),0.028578,0.155547,0.015901,0.556393,3.577009,0.011455,1.903606,2
141,"(Hudson.s.Bay.Corridor.Entrance, Hudson.s.Bay....",(Hudson.s.Bay),0.027652,0.269056,0.015901,0.575026,2.137200,0.008461,1.719974,2
170,"(The.Cheesecake.Factory, Victorias.Secret)",(Hudson.s.Bay),0.021493,0.269056,0.014056,0.653975,2.430629,0.008273,2.112401,2
156,"(The.Cheesecake.Factory.Entrance, Hudson.s.Bay...",(Hudson.s.Bay),0.018442,0.269056,0.013776,0.746983,2.776314,0.008814,2.888917,2
161,"(Hudson.s.Bay.Corridor, Victorias.Secret)",(Hudson.s.Bay),0.020840,0.269056,0.013711,0.657940,2.445367,0.008104,2.136889,2
138,"(Harry.Rosen, Hudson.s.Bay.Corridor)",(Hudson.s.Bay),0.020430,0.269056,0.012584,0.615952,2.289311,0.007087,1.903264,2
174,"(Indigo.Entrance, Hudson.s.Bay.Corridor)",(Sport.Chek.Entrance),0.017860,0.178196,0.011895,0.665997,3.737448,0.008712,2.460469,2
124,"(Banana.Republic.Entrance, Hudson.s.Bay.Corridor)",(Hudson.s.Bay),0.017581,0.269056,0.010976,0.624336,2.320473,0.006246,1.945742,2
131,"(Banana.Republic.Entrance, Indigo.Entrance)",(Sport.Chek.Entrance),0.015829,0.178196,0.010732,0.678005,3.804834,0.007911,2.552224,2
177,"(Indigo.Entrance, Indigo)",(Sport.Chek.Entrance),0.013417,0.178196,0.010208,0.760835,4.269661,0.007817,3.436135,2
179,"(Indigo, Sport.Chek.Entrance)",(Indigo.Entrance),0.015965,0.092375,0.010208,0.639388,6.921674,0.008733,2.516906,2

In [ ]:
rules[ (rules['antecedents'].apply(lambda x: 'Eggs' in x)) & (rules['antecedent_len'] >=2) ]