# Playground for Association Rule Learning slides

- Stephen W. Thomas
- Used for MMA 869, MMAI 869, and GMMA 869

In [1]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Example of converting lists into a dataframe

In [2]:
#dataset = pd.read_csv("AR categories.csv")

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder #need to install mlxtend

#te = TransactionEncoder()
#te_ary = te.fit(dataset).transform(dataset)
#df1 = pd.DataFrame(te_ary, columns=te.columns_)
#df1pip

# Read in Data

In [3]:
#df = pd.read_csv("AR categories.csv")

df = pd.read_csv("AR Visits by Visit ID - luxury no ent.csv")

X = df.copy()
X = X.drop(['Unnamed: 0', 'Visit_ID', 'Visit_ID_AR', 'Dine.on.3', 'Customer_ID', 'Hudson.s.Bay.Corridor', 'West.Expansion.Corridor.NS.Entrance.2', 'North.Corridor.Entrance', 'Sport.Chek.Entrance', 'Indigo.Entrance', 'Banana.Republic.Entrance', 'West.Expansion.NS.Corridor.Entrance.1', 'The.Cheesecake.Factory.Entrance','Crate.and.Barrel.Entrance','Hudson.s.Bay.Corridor.Entrance'], axis=1) #axis 0 to drop rows


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139302 entries, 0 to 139301
Columns: 244 entries, Unnamed: 0 to Customer_ID
dtypes: bool(241), float64(1), int64(2)
memory usage: 35.2 MB

In [ ]:
X.head()
X.shape

In [4]:
from mlxtend.frequent_patterns import apriori

%time frequent_itemsets = apriori(X, min_support=0.005, use_colnames=True)

Wall time: 15.2 s

In [ ]:
frequent_itemsets.head(10)

In [ ]:
frequent_itemsets.tail(10)

In [5]:
frequent_itemsets.sort_values(by=['support'], ascending=False).head()

      support                  itemsets
74   0.269056            (Hudson.s.Bay)
65   0.080530            (Holt.Renfrew)
175  0.078577  (The.Cheesecake.Factory)
64   0.077616             (Harry.Rosen)
128  0.074213               (Nordstrom)

In [ ]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

In [ ]:
frequent_itemsets.head()

In [ ]:
frequent_itemsets[ (frequent_itemsets['length'] >= 2)  ]

In [6]:
from mlxtend.frequent_patterns import association_rules
%time rules = association_rules(frequent_itemsets, min_threshold=0.01)

Wall time: 7.48 ms

In [7]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(Hudson.s.Bay),(Aldo),0.269056,0.017659,0.007380,0.027428,1.553158,0.002628,1.010044,1
1,(Aldo),(Hudson.s.Bay),0.017659,0.269056,0.007380,0.417886,1.553158,0.002628,1.255672,1
2,(Hudson.s.Bay),(Aldo.Accessories),0.269056,0.018995,0.007789,0.028949,1.524045,0.002678,1.010251,1
3,(Aldo.Accessories),(Hudson.s.Bay),0.018995,0.269056,0.007789,0.410053,1.524045,0.002678,1.239000,1
4,(Geox),(American.Eagle.Outfitters),0.033237,0.035190,0.005958,0.179266,5.094260,0.004789,1.175545,1
...,...,...,...,...,...,...,...,...,...,...
341,"(The.Cheesecake.Factory, Victorias.Secret)",(Hudson.s.Bay),0.021493,0.269056,0.014056,0.653975,2.430629,0.008273,2.112401,2
342,"(Hudson.s.Bay, The.Cheesecake.Factory)",(Victorias.Secret),0.042232,0.055656,0.014056,0.332823,5.980003,0.011705,1.415433,2
343,(Victorias.Secret),"(Hudson.s.Bay, The.Cheesecake.Factory)",0.055656,0.042232,0.014056,0.252547,5.980003,0.011705,1.281376,1
344,(Hudson.s.Bay),"(The.Cheesecake.Factory, Victorias.Secret)",0.269056,0.021493,0.014056,0.052241,2.430629,0.008273,1.032443,1
345,(The.Cheesecake.Factory),"(Hudson.s.Bay, Victorias.Secret)",0.078577,0.030660,0.014056,0.178878,5.834250,0.011647,1.180507,1

In [ ]:
rules.sort_values(by=['confidence'], ascending=False).head(10)

In [8]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.1) &
       (rules['lift'] > 1.1) ].sort_values(by="support", ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
340,"(Hudson.s.Bay, Victorias.Secret)",(The.Cheesecake.Factory),0.030660,0.078577,0.014056,0.458441,5.834250,0.011647,1.701425,2
341,"(The.Cheesecake.Factory, Victorias.Secret)",(Hudson.s.Bay),0.021493,0.269056,0.014056,0.653975,2.430629,0.008273,2.112401,2
342,"(Hudson.s.Bay, The.Cheesecake.Factory)",(Victorias.Secret),0.042232,0.055656,0.014056,0.332823,5.980003,0.011705,1.415433,2
328,"(Hudson.s.Bay, The.Cheesecake.Factory)",(Harry.Rosen),0.042232,0.077616,0.006662,0.157743,2.032359,0.003384,1.095134,2
329,"(Hudson.s.Bay, Harry.Rosen)",(The.Cheesecake.Factory),0.033697,0.078577,0.006662,0.197699,2.515978,0.004014,1.148475,2
330,"(The.Cheesecake.Factory, Harry.Rosen)",(Hudson.s.Bay),0.010115,0.269056,0.006662,0.658623,2.447906,0.003940,2.141165,2
334,"(Hudson.s.Bay, Victorias.Secret)",(Harry.Rosen),0.030660,0.077616,0.006116,0.199485,2.570167,0.003737,1.152239,2
335,"(Hudson.s.Bay, Harry.Rosen)",(Victorias.Secret),0.033697,0.055656,0.006116,0.181508,3.261250,0.004241,1.153761,2
336,"(Victorias.Secret, Harry.Rosen)",(Hudson.s.Bay),0.009662,0.269056,0.006116,0.632987,2.352623,0.003516,1.991601,2

In [ ]:
rules[ (rules['antecedents'].apply(lambda x: 'Microsoft' in x)) & (rules['antecedent_len'] >=1) ]

In [9]:
rules.to_csv(r'Luxury Customer Stores Rules.csv')