# Playground for Association Rule Learning slides

- Stephen W. Thomas
- Used for MMA 869, MMAI 869, and GMMA 869

In [6]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Example of converting lists into a dataframe

In [7]:
#dataset = pd.read_csv("AR categories.csv")

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder #need to install mlxtend

#te = TransactionEncoder()
#te_ary = te.fit(dataset).transform(dataset)
#df1 = pd.DataFrame(te_ary, columns=te.columns_)
#df1pip

# Read in Data

In [36]:
#df = pd.read_csv("AR categories.csv")

df = pd.read_csv("AR Visits by Visit ID - luxury no ent.csv")

X = df.copy()
X = X.drop(['Unnamed: 0', 'Visit_ID', 'Visit_ID_AR', 'Dine.on.3', 'Customer_ID', 'Hudson.s.Bay.Corridor', 'West.Expansion.Corridor.NS.Entrance.2', 'North.Corridor.Entrance', 'Sport.Chek.Entrance', 'Indigo.Entrance', 'Banana.Republic.Entrance', 'Hudson.s.Bay', 'Victorias.Secret','The.Cheesecake.Factory'], axis=1) #axis 0 to drop rows


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139302 entries, 0 to 139301
Columns: 244 entries, Unnamed: 0 to Customer_ID
dtypes: bool(241), float64(1), int64(2)
memory usage: 35.2 MB

In [ ]:
X.head()
X.shape

In [41]:
from mlxtend.frequent_patterns import apriori

%time frequent_itemsets = apriori(X, min_support=0.005, use_colnames=True)

Wall time: 10.9 s

In [ ]:
frequent_itemsets.head(10)

In [ ]:
frequent_itemsets.tail(10)

In [42]:
frequent_itemsets.sort_values(by=['support'], ascending=False).head()

      support                           itemsets
66   0.080530                     (Holt.Renfrew)
65   0.077616                      (Harry.Rosen)
129  0.074213                        (Nordstrom)
146  0.066431             (Restoration.Hardware)
176  0.065039  (The.Cheesecake.Factory.Entrance)

In [43]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

In [ ]:
frequent_itemsets.head()

In [44]:
frequent_itemsets[ (frequent_itemsets['length'] >= 2)  ]

      support                                           itemsets  length
204  0.005958                  (Geox, American.Eagle.Outfitters)       2
205  0.007164                               (Club.Monaco, Apple)       2
206  0.006066                               (Harry.Rosen, Apple)       2
207  0.007186                              (Holt.Renfrew, Apple)       2
208  0.007774                    (Holt.Renfrew.Back.Door, Apple)       2
209  0.005118                                 (Nordstrom, Apple)       2
210  0.009863                                (North.Face, Apple)       2
211  0.006087                              (Tesla.Motors, Apple)       2
212  0.005822                               (Aveda, Harry.Rosen)       2
213  0.007724                  (Banana.Republic, Crate...Barrel)       2
214  0.005843                   (Banana.Republic, Mac.Cosmetics)       2
215  0.005327                                 (Birks, Nordstrom)       2
216  0.017882                          (Nordstrom, Canada.Goose)       2
217  0.005994                             (Sandro, Canada.Goose)       2
218  0.006425                    (Mac.Cosmetics, Crate...Barrel)       2
219  0.005240           (Harry.Rosen, Crate.and.Barrel.Entrance)       2
220  0.005305          (Holt.Renfrew, Crate.and.Barrel.Entrance)       2
221  0.005075             (Nordstrom, Crate.and.Barrel.Entrance)       2
222  0.005607  (Crate.and.Barrel.Entrance, Restoration.Hardware)       2
223  0.005793  (The.Cheesecake.Factory.Entrance, Crate.and.Ba...       2
224  0.005212                (Crate.and.Barrel.Entrance, Uniqlo)       2
225  0.005075                          (Harry.Rosen, Forever.21)       2
226  0.005298      (The.Cheesecake.Factory.Entrance, Forever.21)       2
227  0.005190                            (Harry.Rosen, Gap.Kids)       2
228  0.005664                                (Geox, Harry.Rosen)       2
229  0.006482                        (Holt.Renfrew, Harry.Rosen)       2
230  0.006884      (Hudson.s.Bay.Corridor.Entrance, Harry.Rosen)       2
231  0.005126                          (North.Face, Harry.Rosen)       2
232  0.005305                       (Sporting.Life, Harry.Rosen)       2
233  0.006726     (The.Cheesecake.Factory.Entrance, Harry.Rosen)       2
234  0.005205                              (Harry.Rosen, Uniqlo)       2
235  0.005312     (Hudson.s.Bay.Corridor.Entrance, Holt.Renfrew)       2
236  0.005484                          (Nordstrom, Holt.Renfrew)       2
237  0.005951                         (Holt.Renfrew, North.Face)       2
238  0.005930    (The.Cheesecake.Factory.Entrance, Holt.Renfrew)       2
239  0.006533                             (Holt.Renfrew, Uniqlo)       2
240  0.006705  (Hudson.s.Bay.Corridor.Entrance, Restoration.H...       2
241  0.009332  (Hudson.s.Bay.Corridor.Entrance, Shoppers.Drug...       2
242  0.006238  (Hudson.s.Bay.Corridor.Entrance, The.Cheesecak...       2
243  0.006741  (Hudson.s.Bay.Corridor.Entrance, West.Expansio...       2
244  0.009634             (Microsoft, Joey.Restaurants.Entrance)       2
245  0.005757                   (Nordstrom, Lululemon.Athletica)       2
246  0.009404                                (Sandro, Nordstrom)       2
247  0.005413       (Nordstrom, The.Cheesecake.Factory.Entrance)       2
248  0.007918                                (Nordstrom, Uniqlo)       2
249  0.005097                                  (Nordstrom, Zara)       2
250  0.005183            (Raffi.Jewellers, Restoration.Hardware)       2
251  0.011328              (Sporting.Life, Restoration.Hardware)       2
252  0.005133  (The.Cheesecake.Factory.Entrance, Restoration....       2
253  0.009885  (Restoration.Hardware, West.Expansion.NS.Corri...       2
254  0.006935  (West.Expansion.West.Entrance, Restoration.Har...       2
255  0.005685          (The.Cheesecake.Factory.Entrance, Uniqlo)       2

In [46]:
from mlxtend.frequent_patterns import association_rules
%time rules = association_rules(frequent_itemsets, min_threshold=0.01)

Wall time: 6.83 ms

In [47]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(Geox),(American.Eagle.Outfitters),0.033237,0.035190,0.005958,0.179266,5.094260,0.004789,1.175545,1
1,(American.Eagle.Outfitters),(Geox),0.035190,0.033237,0.005958,0.169319,5.094260,0.004789,1.163819,1
2,(Club.Monaco),(Apple),0.020904,0.060315,0.007164,0.342720,5.682165,0.005903,1.429657,1
3,(Apple),(Club.Monaco),0.060315,0.020904,0.007164,0.118781,5.682165,0.005903,1.111070,1
4,(Harry.Rosen),(Apple),0.077616,0.060315,0.006066,0.078154,1.295762,0.001385,1.019351,1
...,...,...,...,...,...,...,...,...,...,...
99,(West.Expansion.NS.Corridor.Entrance.1),(Restoration.Hardware),0.030552,0.066431,0.009885,0.323543,4.870350,0.007855,1.380086,1
100,(West.Expansion.West.Entrance),(Restoration.Hardware),0.014594,0.066431,0.006935,0.475160,7.152660,0.005965,1.778768,1
101,(Restoration.Hardware),(West.Expansion.West.Entrance),0.066431,0.014594,0.006935,0.104387,7.152660,0.005965,1.100259,1
102,(The.Cheesecake.Factory.Entrance),(Uniqlo),0.065039,0.061227,0.005685,0.087417,1.427763,0.001703,1.028699,1
103,(Uniqlo),(The.Cheesecake.Factory.Entrance),0.061227,0.065039,0.005685,0.092860,1.427763,0.001703,1.030669,1

In [55]:
rules.sort_values(by=['confidence'], ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
100,(West.Expansion.West.Entrance),(Restoration.Hardware),0.014594,0.066431,0.006935,0.475160,7.152660,0.005965,1.778768,1
84,(Sandro),(Nordstrom),0.022397,0.074213,0.009404,0.419872,5.657669,0.007742,1.595832,1
22,(Birks),(Nordstrom),0.012692,0.074213,0.005327,0.419683,5.655128,0.004385,1.595314,1
25,(Canada.Goose),(Nordstrom),0.049088,0.074213,0.017882,0.364288,4.908688,0.014239,1.456299,1
28,(Mac.Cosmetics),(Crate...Barrel),0.018586,0.054572,0.006425,0.345693,6.334619,0.005411,1.444931,1
2,(Club.Monaco),(Apple),0.020904,0.060315,0.007164,0.342720,5.682165,0.005903,1.429657,1
99,(West.Expansion.NS.Corridor.Entrance.1),(Restoration.Hardware),0.030552,0.066431,0.009885,0.323543,4.870350,0.007855,1.380086,1
21,(Mac.Cosmetics),(Banana.Republic),0.018586,0.034386,0.005843,0.314407,9.143536,0.005204,1.408437,1
80,(Microsoft),(Joey.Restaurants.Entrance),0.030847,0.032526,0.009634,0.312311,9.601751,0.008630,1.406847,1
75,(Shoppers.Drug.Mart),(Hudson.s.Bay.Corridor.Entrance),0.031486,0.058542,0.009332,0.296398,5.063002,0.007489,1.338054,1

In [51]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.1) &
       (rules['lift'] > 1.1) ].sort_values(by="support", ascending=False)

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, antecedent_len]
Index: []

In [58]:
rules[ (rules['antecedents'].apply(lambda x: 'Microsoft' in x)) & (rules['antecedent_len'] >=1) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
80,(Microsoft),(Joey.Restaurants.Entrance),0.030847,0.032526,0.009634,0.312311,9.601751,0.00863,1.406847,1